final_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("federations.urls")),
    path('', include("teams.urls")),
    path('', include("players.urls")),
            
    ]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from home import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("about/", views.about, name="about"),
    path('login', views.login_required, name='login'),
    path('register', views.register, name='user-register'),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

players/urls.py
from django.urls import path

from players import views

app_name = "players"

urlpatterns = [
#    path("players", views.players, name="players-list"),
#    path("player/add", views.create_player, name="player-add"),

    path("player/add/", views.PlayerCreateView.as_view(), name="player-add"),
    path("players/", views.PlayerListView.as_view(), name="players-list"),
    path("player/<int:pk>/detail/", views.PlayerDetailView.as_view(), name="player-detail"),
    path("player/<int:pk>/update/", views.PlayerUpdateView.as_view(), name="player-update"),
    path("player/<int:pk>/delete/", views.PlayerDeleteView.as_view(), name="player-delete"),

    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

players/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models


# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    team = models.CharField(max_length=40)
    number = models.IntegerField()
    position = models.CharField(max_length=40)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        unique_together = (
            "name",
            "last_name",
        )
        ordering = ["-last_name"]
    
    def  __str__(self):
        return f"{self.name} - {self.last_name} - {self.number}"

class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

players/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from players.models import Player

class PlayerForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "player-name",
                "placeholder": "Nombre",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "player-last_name",
                "placeholder": "Apellido",
                "required": "True",
            }
        ),
    )
    team = forms.CharField(
        label="Equipo",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "team-name",
                "placeholder": "Equipo",
                "required": "True",
            }
        ),
    )
    number = forms.IntegerField(
        label="Número",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "number-name",
                "placeholder": "Número",
                "required": "True",
            }
        ),
    )
    position = forms.CharField(
        label="Posición",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "position-name",
                "placeholder": "Posición",
                "required": "True",
            }
        ),
    )
    class Meta:
        model = Player
        fields = ["name", "last_name", "team", "number", "position"] 
    

class CommentForm(forms.Form):
    comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )

players/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from players.models import Player
from players.forms import PlayerForm
from players.models import Comment
from players.forms import CommentForm

# Create your views here.
class PlayerListView(ListView):
    model = Player
    template_name = "players/players_list.html"
    paginate_by = 3


class PlayerCreateView(LoginRequiredMixin,CreateView):
    model = Player
    success_url = reverse_lazy("players:players-list")

    form_class = PlayerForm

    def form_valid(self, form):
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Player.objects.filter(
            name=data["name"], last_name=data["last_name"],).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El jugador {data['name']} {data['last_name']} ya se encuentra en la base de datos",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Jugador {data['name']} {data['last_name']} incluido exitosamente!",
            )
            return super().form_valid(form)
        
class PlayerDetailView(DetailView):
    model = Player
    template_name = "players/player_detail.html"
    fields = ["name", "last_name", "team", "number", "position"]

    def get(self, request, pk):
        player = Player.objects.get(id=pk)
        comments = Comment.objects.filter(player=player).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "player": player,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)
    
class PlayerUpdateView(LoginRequiredMixin,UpdateView):
    model = Player
    fields = ["name", "last_name", "team", "number", "position"]

    def get_success_url(self):
        player_id = self.kwargs["pk"]
        return reverse_lazy("players:player-detail", kwargs={"pk": player_id})

class PlayerDeleteView(LoginRequiredMixin,DeleteView):
    model = Player
    success_url = reverse_lazy("players:players-list")

class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        player = get_object_or_404(Player, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, player=player
        )
        comment.save()
        return redirect(reverse("players:player-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        player = self.object.player
        return reverse("players:player-detail", kwargs={"pk": player.id})

players/templates/players/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Comment delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/PLAYERS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'players:player-detail' comment.player.id %}" >Cancelar</a>
</form>

{% endblock %}

players/templates/players/player_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Player delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/PLAYERS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ player.name }} {{ player.last_name }}</h1>
                    <span class="subheading">Eliminar jugador</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar al jugador: {{ player.name }} {{ player.last_name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'players:players-list' %}" >Cancelar</a>
</form>

{% endblock %}

players/templates/players/player_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Player detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/PLAYERS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ player.name }}</h1>
                    <span class="subheading">Detalles del jugador</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'players:player-add' %}">Incluir nuevo jugador</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <center>
        <h1 class="post-title">{{ player.name }} {{ player.last_name }}</h3>
    </center>
    <h3 class="post-subtitle">Equipo: {{ player.team }}</h3>
    <h3 class="post-subtitle">Número: {{ player.number }}</h3>
    <h3 class="post-subtitle">Posición: {{ player.position }}</h3>
    <p class="post-meta">
        Creado por
        <span style="color: #0b4956;" href="">{{ player.owner.username }}</span>
        ( {{ player.created_at }} )
        <br>
        Última fecha de actualización ( {{ player.updated_at }} )
    </p>
    

    <!-- Update-Delete link only for the owner -->
    {% if user == course.owner or user.is_superuser %}
        <p style="text-align: center">
            <a href="{% url 'players:player-update' player.id %}">
                <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
            </a>
            &ensp; | &ensp;
            <a href="{% url 'players:player-delete' player.id %}">
                    <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar
            </a>
        </p>
    {% endif %}

    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="POST" action="{% url 'players:comment-create' player.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'players:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}


</div>
{% endblock %}

players/templates/players/player_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Players
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/PLAYERS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para incluir un jugador</h2>
                    <span class="subheading">FIFA</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar jugador" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

players/templates/players/players_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Players
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('../../static/home/assets/img/PLAYERS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar un equipo</h2>
                    <span class="subheading">FIFA</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar jugador" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

players/templates/players/players_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Players
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/PLAYERS.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Jugadores</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'players:player-add' %}">Incluir nuevo jugador</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% if not player_list %}
        <div class="small text-center text-muted fst-italic">No existen jugadores en la base de datos para mostrar</div>
    {% endif %}
    {% for player in player_list %}
    <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'players:player-detail' player.id %}">
                <center>
                    <h1 class="post-title">{{ player.name }} {{ player.last_name }}</h3>
                </center>
            </a>
            <h3 class="post-subtitle">Equipo: {{ player.team }}</h3>
            <h3 class="post-subtitle">Número: {{ player.number }}</h3>
            <h3 class="post-subtitle">Posición: {{ player.position }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}