federations/urls.py
from django.urls import path

from federations import views

app_name = "federations"

urlpatterns = [
    path("federations", views.federations, name="federations-list"),
    path("federation/add", views.create_federation, name="federation-add"),
    path("federation/<int:pk>/detail/", views.federation_detail, name="federation-detail"),
    path("federation/<int:pk>/update/", views.federation_update, name="federation-update"),
    path("federation/<int:pk>/delete/", views.federation_delete, name="federation-delete"),
]

final_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("federations.urls")),
    path('', include("teams.urls")),
    path('', include("players.urls")),
            
    ]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from home import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("about/", views.about, name="about"),
    path('login', views.login_required, name='login'),
    path('register', views.register, name='user-register'),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

players/urls.py
from django.urls import path

from players import views

app_name = "players"

urlpatterns = [
#    path("players", views.players, name="players-list"),
#    path("player/add", views.create_player, name="player-add"),

    path("player/add/", views.PlayerCreateView.as_view(), name="player-add"),
    path("players/", views.PlayerListView.as_view(), name="players-list"),
    path("player/<int:pk>/detail/", views.PlayerDetailView.as_view(), name="player-detail"),
    path("player/<int:pk>/update/", views.PlayerUpdateView.as_view(), name="player-update"),
    path("player/<int:pk>/delete/", views.PlayerDeleteView.as_view(), name="player-delete"),

    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

teams/urls.py
from django.urls import path

from teams import views

app_name = "teams"

urlpatterns = [
    path("teams", views.teams, name="teams-list"),
    path("team/add", views.create_team, name="team-add"),
]

home/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatar', null=True, blank=True)

    def __str__(self):
        return f'user: {self.user.username} | url: {self.image.url}'
# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from home.models import Avatar

class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label="username", min_length=3)
    first_name = forms.CharField(label="Nombre", min_length=3)
    last_name = forms.CharField(label="Apellido", min_length=3)
    email = forms.EmailField(label="Correo electrónico")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "email": forms.TextInput(attrs={"readonly": "readonly"}),
        }


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ("image", )






class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label="username", min_length=3)
    first_name = forms.CharField(label="Nombre", min_length=3)
    last_name = forms.CharField(label="Apellido", min_length=3)
    email = forms.EmailField(label="Correo electrónico")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Password", widget=forms.PasswordInput)

    last_name = forms.CharField()
    first_name = forms.CharField() 
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'last_name', 'first_name']
    
        help_texts = {k:"" for k in fields}

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "email": forms.TextInput(attrs={"readonly": "readonly"}),
        }


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ("image", )

home/views.py
import os
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.shortcuts import render

from federations.models import Federation
from home.models import Avatar
from home.forms import AvatarForm
from home.forms import UserRegisterForm
from home.forms import UserUpdateForm

#from home.forms import AvatarForm

def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

def about(request):
    return render(
        request=request,
        context={},
        template_name="home/about.html",
    )

def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add(Q(official_website__contains=search_param), Q.OR)
        federations = Federation.objects.filter(query)
        context_dict.update(
            {
                "federations": federations,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )


def register(request):
    form = UserRegisterForm(request.POST) if request.POST else UserRegisterForm()
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("login")

    return render(
        request=request,
        context={"form": form},
        template_name="registration/register.html",
    )


@login_required
def user_update(request):
    user = request.user
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("home:index")

    form = UserUpdateForm(model_to_dict(user))
    return render(
        request=request,
        context={"form": form},
        template_name="registration/user_form.html",
    )

@login_required
def avatar_load(request):
    if request.method == "POST":
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid and len(request.FILES) != 0:
            image = request.FILES["image"]
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect("home:index")

    form = AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="home/avatar_form.html",
    )

def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"avatar_url": avatars[0].image.url}
    return {}

home/templates/home/about.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Acerca de
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('../../static/home/assets/img/PLAYERS.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Quienes somos</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    <!-- Post preview-->
    <center>
        <h1 class="post-title">Orellano Julio</h3>
    </center>        
    <h3 class="post-subtitle">Ingeniero en automatización y control industrial buscando nuevos horizontes en el desarrollo de software. </h3>
    <!-- Divider-->
    <hr class="my-4" />
    <center>
        <h1 class="post-title">Mario Reggiardo</h3>
    </center>
    <h3 class="post-subtitle">XXXXXXXXXXXXXXXXXXXXXXXX</h3>
    <!-- Divider-->
    <hr class="my-4" />
    <center>
        <h1 class="post-title">El proyecto</h3>
    </center>
    <h3 class="post-subtitle">El proyecto se trata de un blog de la FIFA en el cual se encuentran las federaciones de fútbol, equipos y jugadores. </h3>

    
{% endblock %}

home/templates/home/avatar_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Avatar Load
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Cargar Imagen de Avatar</h1>
                    <span class="subheading">Fédération Internationale de Football Association</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
    <h1>Usuario: {{user.username}} | {{user.first_name}} {{user.last_name}}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Cargar Imagen</button>
    </form>
{% endblock %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block my_blog_title %}
                Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/pelota.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">HOME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'federations:federations-list' %}">Federaciones</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'teams:teams-list' %}">Equipos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'players:players-list' %}">Jugadores</a></li>   
                        
                        <div class="topbar-divider d-none d-sm-block"></div>
                        
                        {% if not user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:user-register' %}">Registrate</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:user-update' %}">Editar usuario</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Cerrar Sesión - {{ user.username }}</a></li>                  
                        {% else %}
                        <!--<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:login' %}">Iniciar Sesión</a></li>-->
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">Iniciar Sesión</a></li>
                        {% endif %}
                    </ul>

                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block my_blog_header %}
        <header class="masthead" style="background-image: url('../../static/home/assets/img/FIFA.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            {% if user.is_authenticated %}
                                <h3>Bienvenido {{ user.first_name }} {{ user.last_name }}</h3>
                            {% else %}
                                <h2>Bienvenido</h2>
                                <span class="subheading">Registrese o inicie sesion para continuar</span>
                            {% endif %}
                            {% if avatar_url %}
                                <a href="{% url 'home:avatar' %}"><img height="260px" src="{{avatar_url}}"></a>
                            {% endif %}
 
                            <h1>FIFA</h1>
                            <span class="subheading">Fédération Internationale de Football Association</span>
                              
                        </div>

                    </div>
                </div>
                 <!-- <div style="background-color: #ffffff; width: 87%;" color>Avatar URL: {{ avatar_url }}</div> -->
                 {% if not avatar_url %}
             {% endif %}
            </div>
        </header>
        {% endblock %}
        <!-- Messages-->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% block my_blog_content %}

                    <!-- Buscador -->
                    <h2>Buscador de federaciones</h2>
                    <form action="{% url 'home:search' %}" method="GET">
                        <div>
                            <input type="text" name="search_param" id="course_code_or_name" placeholder="Buscar.."
                            {% if search_param %} value="{{ search_param }}" {% endif %}
                            >
                            <input type="submit" value="Buscar">
                            <a style="color: blue" href="{% url 'home:index' %}"><i class="fa fa-undo"></i></a>
                        </div>
                    </form>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Si hay resultados en el buscador los presenta -->
                    {% if federations %}
                    {% for federation in federations %}
                        <!-- Post preview-->
                        <div class="post-preview">
                            <h2 class="post-title">Federación: {{ federation.name }}</h2>
                            <h3 class="post-subtitle">Sigla: {{ federation.initials }}</h3>
                            <p class="post-meta">
                                Creado por
                                <a href="#!">FIFA</a> 
                            </p>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endfor %}
                    {% endif %}
                    
                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="{% url 'home:about' %}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-info fa-stack-1x fa-inverse"></i>
                                    </span>
                                    conocenos
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>