federations/urls.py
from django.urls import path

from federations import views

app_name = "federations"

urlpatterns = [
    path("federations", views.federations, name="federations-list"),
    path("federation/add", views.create_federation, name="federation-add"),
    path("federation/<int:pk>/detail/", views.federation_detail, name="federation-detail"),
    path("federation/<int:pk>/update/", views.federation_update, name="federation-update"),
    path("federation/<int:pk>/delete/", views.federation_delete, name="federation-delete"),
]

final_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("federations.urls")),
    path('', include("teams.urls")),
    path('', include("players.urls")),
            
    ]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from home import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("about/", views.about, name="about"),
    path('login', views.login_required, name='login'),
    path('register', views.register, name='user-register'),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

federations/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Federation(models.Model):
    name = models.CharField(max_length=40)
    initials = models.CharField(max_length=40)
    official_website = models.CharField(max_length=40)
    image = models.ImageField(upload_to = "shields", null = True, blank= True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def  __str__(self):
        return f"{self.initials} - {self.name}"

federations/forms.py
from django import forms
from federations.models import Federation

class FederationForm(forms.Form):
    name = forms.CharField(
        label="Nombre de la federación",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "federation-name",
                "placeholder": "Nombre de la federación",
                "required": "True",
            }
        ),
    )
    initials = forms.CharField(
        label="Sigla de la federación",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "federations-initials",
                "placeholder": "Sigla de la federación",
                "required": "True",
            }
        ),
    )
    official_website = forms.CharField(
        label="Sitio oficial",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "federations-website",
                "placeholder": "Sitio oficial",
                "required": "True",
            }
        ),
    )
    image = forms.ImageField(required=False)

    class Meta:
        model = Federation
        fields = ["name", "initials", "official_website", "image"]
    

federations/views.py
from django.forms.models import model_to_dict
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from federations.models import Federation
from federations.forms import FederationForm


# Create your views here.
def federations(request):
    federations = Federation.objects.all()

    context_dict = {"federations": federations}

    return render(
        request = request,
        context = context_dict,
        template_name="federations/federations_list.html",
    )

@login_required
def create_federation(request):
    if request.method == "POST":
        federation_form = FederationForm(request.POST, request.FILES)
        if federation_form.is_valid() and len(request.FILES) != 0:
            image = request.FILES["image"]
            data = federation_form.cleaned_data
            actual_objects = Federation.objects.filter(
                name=data["name"], initials=data["initials"], official_website=data["official_website"]
            ).count()
            if actual_objects:
                messages.error(
                    request,
                    f"La federación {data['name']} - {data['initials']} ya existe",
                )
            else:
                federation = Federation(name=data["name"], initials=data["initials"], official_website=data["official_website"], image=image, owner=request.user)
                federation.save()
                messages.success(
                    request,
                    f"Federación {data['name']} - {data['initials']} incluida exitosamente!",
                )

            federations = Federation.objects.all()

            context_dict = {"federations": federations}

            return render(
                request=request,
                context=context_dict,
                template_name="federations/federations_list.html",
            )

    federation_form = FederationForm(request.POST)
    context_dict = {"form": federation_form}
    return render(
        request=request,
        context=context_dict,
        template_name="federations/federations_form.html",
    )

def federation_detail(request, pk: int):
    return render(
        request=request,
        context={"federation": Federation.objects.get(pk=pk)},
        template_name="federations/federation_detail.html",
    )

@login_required
def federation_update(request, pk: int):
    federation = Federation.objects.get(pk=pk)

    if request.method == "POST":
        federation_form = FederationForm(request.POST, request.FILES)
        if federation_form.is_valid():
            data = federation_form.cleaned_data
            federation.name = data["name"]
            federation.initials = data["initials"]
            federation.official_website = data["official_website"]
            federation.image = data["image"]
            federation.save()

            return render(
                request=request,
                context={"federation": federation},
                template_name="federations/federation_detail.html",
            )

    federation_form = FederationForm(model_to_dict(federation))
    context_dict = {
        "federation": federation,
        "form": federation_form,
    }
    return render(
        request=request,
        context=context_dict,
        template_name="federations/federations_form.html",
    )

@login_required
def federation_delete(request, pk: int):
    federation = Federation.objects.get(pk=pk)
    if request.method == "POST":
        federation.delete()

        federations = Federation.objects.all()
        context_dict = {"federations": federations}
        return render(
            request=request,
            context=context_dict,
            template_name="federations/federations_list.html",
        )

    context_dict = {
        "federation": federation,
    }
    return render(
        request=request,
        context=context_dict,
        template_name="federations/federation_confirm_delete.html",
    )

federations/templates/federations/federation_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
federation delete
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/FIFA.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Eliminar federación</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'federations:federation-add' %}">Incluir</a>
        </div>
    </header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar la federación: {{ federation.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'federations:federations-list' %}" >Cancelar</a>
</form>

{% endblock %}

federations/templates/federations/federation_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Federations
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/FIFA.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Detalle de Federacion</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'federations:federation-add' %}">Incluir</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
        <!-- Post preview-->
    <div class="post-preview">
        <center>
            <h3 class="post-subtitle">{{ federation.name }} </h3>
            <h3 class="post-subtitle">{{ federation.initials }} </h3>
        </center>
        <!-- Image -->
        {% if federation.image %}
            <div style="text-align: center;">
                <img height="250px" src="{{ federation.image.url }}">
            </div>
        {% endif %}
        <p class="card-text ">{{ federation.description|safe }}</p> <!-- ckeditor-->
        {% if user == federation.owner or user.is_superuser %}
            <p style="text-align: center">
                <a href="{% url 'federations:federation-update' federation.id %}">
                    <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
                </a>
                &ensp; | &ensp;
                <a href="{% url 'federations:federation-delete' federation.id %}">
                    <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
                </a>
            </p>
        {% endif %}
    </div>
{% endblock %}

federations/templates/federations/federations_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Federations
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/FIFA.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar una federación</h2>
                    <span class="subheading">FIFA</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar federación" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

federations/templates/federations/federations_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Federations
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/FIFA.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Federaciones</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'federations:federation-add' %}">Incluir</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
{% if not federations %}
        <div class="small text-center text-muted fst-italic">No existen federaciones en la base de datos para mostrar</div>
{% endif %}
{% for federation in federations %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'federations:federation-detail' federation.id %}">
                <h3 class="post-title">Federación: {{ federation.name }} </h3>
                <h3 class="post-subtitle">Sigla: {{ federation.initials }}</h3>
            </a>
            <h3 class="post-subtitle">Sitio oficial: {{ federation.official_website }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}