final_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("federations.urls")),
    path('', include("teams.urls")),
    path('', include("players.urls")),
            
    ]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from home import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("about/", views.about, name="about"),
    path('login', views.login_required, name='login'),
    path('register', views.register, name='user-register'),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

teams/urls.py
from django.urls import path

from teams import views

app_name = "teams"

urlpatterns = [
    path("teams", views.teams, name="teams-list"),
    path("team/add", views.create_team, name="team-add"),
]

teams/models.py
from django.db import models
from federations.models import Federation
# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=40)
    federation = models.ForeignKey(Federation, 
                                    on_delete=models.CASCADE,
                                    null=False,
                                    blank=False)
    country = models.CharField(max_length=40)
    city = models.CharField(max_length=40)
    fundation_date = models.DateField()

    def  __str__(self):
        return f"{self.name} - {self.country}"

teams/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from federations.models import Federation
from datetime import datetime

MONTHS = {
    1:'enero', 2:'febrero', 3:'marzo', 4:'abril',
    5:'mayo', 6:'junio', 7:'julio', 8:'agosto',
    9:'septiembre', 10:'octubre', 11:'noviembre', 12:'diciembre'
}

class TeamForm(forms.Form):
    name = forms.CharField(
        label="Nombre del equipo",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "team-name",
                "placeholder": "Nombre del equipo",
                "required": "True",
            }
        ),
    )
    federation = forms.ModelChoiceField(queryset= Federation.objects.all(),
        label="Federacion de pertenencia",
        required=False,
        widget=forms.Select(
            attrs={
                "class": "federation-name",
                "placeholder": "Federacion de pertenencia",
                "required": "True",
            }
        ),
    )
    country = forms.CharField(
        label="Pais de origen",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "country-name",
                "placeholder": "Pais de origen",
                "required": "True",
            }
        ),
    )
    city = forms.CharField(
        label="Ciudad",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "country-name",
                "placeholder": "Ciudad",
                "required": "True",
            }
        ),
    )
    fundation_date = forms.DateField(label='Fecha de fundación', 
                                    required=False,
                                    widget=forms.SelectDateWidget(
                                        years=range(1900, datetime.today().year),
                                        months = MONTHS,
                                        empty_label=("Año", "Mes", "Dia"),
                                    ),
    )
    

teams/views.py
from django.shortcuts import render
from django.contrib import messages
from teams.models import Team
from teams.forms import TeamForm


# Create your views here.
def teams(request):
    teams = Team.objects.all()

    context_dict = {"teams": teams}

    return render(
        request = request,
        context = context_dict,
        template_name="teams/teams_list.html",
    )

def create_team(request):
    if request.method == "POST":
        team_form = TeamForm(request.POST)
        if team_form.is_valid():
            data = team_form.cleaned_data
            actual_objects = Team.objects.filter(
                name=data["name"], federation=data["federation"], country=data["country"], city=data["city"], fundation_date=data["fundation_date"]
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El equipo {data['name']} ya existe",
                )
            else:
                team = Team(name=data["name"], federation=data["federation"], country=data["country"], city=data["city"], fundation_date=data["fundation_date"])
                team.save()
                messages.success(
                    request,
                    f"Equipo {data['name']}  incluido exitosamente!",
                )

            teams = Team.objects.all()

            context_dict = {"teams": teams}

            return render(
                request=request,
                context=context_dict,
                template_name="teams/teams_list.html",
            )

    team_form = TeamForm(request.POST)
    context_dict = {"form": team_form}
    return render(
        request=request,
        context=context_dict,
        template_name="teams/teams_form.html",
    )

teams/templates/teams/teams_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Teams
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/TEAMS.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar un equipo</h2>
                    <span class="subheading">FIFA</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar equipo" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

teams/templates/teams/teams_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Teams
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/TEAMS.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Equipos</h1>
                        <span class="subheading">My blog CoderHouse</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'teams:team-add' %}">Incluir nuevo equipo</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
{% for team in teams %}
        <!-- Post preview-->
        <div class="post-preview">
            <h3 class="post-title">Equipo: {{ team.name }} </h3>
            <h3 class="post-subtitle">Federación: {{ team.federation }}</h3>
            <h3 class="post-subtitle">País: {{ team.country }}</h3>
            <h3 class="post-subtitle">Ciudad: {{ team.city }}</h3>
            <h3 class="post-subtitle">Fecha de fundación: {{ team.fundation_date }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}